version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SHIPPING_API_KEY=${SHIPPING_API_KEY}
      - SHIPPING_API_BASE_URL=${SHIPPING_API_BASE_URL}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_BASE_URL=${REACT_APP_BACKEND_BASE_URL}
